#pragma once

#include <Core/API.h>
#include <Core/glm.h>
#include <Core/Memory.h>
#include <Renderer/Context.h>
#include <Renderer/Buffer.h>
#include <Renderer/VertexArray.h>
#include <Renderer/Shader.h>
#include <Renderer/PerspectiveCamera.h>
#include <Renderer/ShaderManager.h>
#include <Renderer/Framebuffer.h>
#include <Material/Material.h>
#include <Renderer/GraphicsPipeline.h>
#include <Renderer/GraphicsAPI.h>
#include <DataStructure/Graph.h>
#include <Scene/Entity.h>

namespace atcg
{
class Scene;

/**
 * @brief This class models a renderer. This should be used if you are trying to create multiple renderer instances
 * (e.g. for multi threading). Per default, use atcg::Renderer to use the default renderer.
 */
class ATCG_API RendererSystem
{
public:
    /**
     * @brief Initializes the renderer (should not be called by the client!)
     *
     * @param width The width
     * @param height The height
     * @param context The opengl context
     * @param shader_manager The shader manager associated with this renderer
     */
    void init(uint32_t width,
              uint32_t height,
              const atcg::ref_ptr<Context>& context,
              const atcg::ref_ptr<ShaderManagerSystem>& shader_manager);

    /**
     * @brief Use this instance of the renderer.
     * This only needs to be called if multiple renderer instances are in use or multi thread rendering is desired. This
     * function will make the underlying context current for the thread.
     */
    void use();

    /**
     * @brief Finished the currently drawn frame (should not be called by client!)
     */
    void finishFrame();

    /**
     * @brief Stalls the CPU until all rendering requests are finished
     */
    void finish() const;

    /**
     * @brief Change the size of the renderer
     *
     * @param width The width
     * @param height The height
     */
    void resize(const uint32_t& width, const uint32_t& height);

    /**
     * @brief Get the current frame counter
     *
     * @return The index of the current frame
     */
    uint32_t getFrameCounter() const;

    /**
     * @brief Generates a new texture ID that is not used yet.
     * The renderer internally uses a fixed set of render IDs that should not be used by the client. This function
     * guarantees that the given texture id is not yet taken (unless manual texture ids are created). If a texture id is
     * no longer in use, it should be released with pushTextureID.
     *
     * @return The texture ID
     */
    uint32_t popTextureID();

    /**
     * @brief Free a texture ID.
     * Should only be used on ids that were generated using popTextureID. Adding other IDs may break the system because
     * some ids are reserved for the internals of the Renderer.
     *
     * @param id The id generated by popTextureID
     */
    void pushTextureID(const uint32_t id);

    /**
     * @brief Render a mesh
     *
     * The default draw mode is "base". It applys slight shading based on the vertex normals.
     * An optional color can be given to color the whole mesh with a constant color.
     * If given a custom shader, color is ignored except if the shader variable "flat_color" is used.
     *
     * For ATCG_DRAW_MDOE_SPHERE The custom shader has to implement an instance rendering scheme like the "base" shader.
     * If no custom shader is to be used, stick to the "base" shader. For ATCG_DRAW_MODE_EDGE and
     * ATCG_DRAW_MODE_CYLINDER, you can pass nullptr for the shader to use the built in "edge" and "edge_cylinder"
     * shader. If a custom shader should be used, it has to implement the basic instancing the is used in the
     * aforementioned shaders.
     *
     * @param mesh The mesh
     * @param camera The camera
     * @param model The optional model matrix
     * @param color An optional color
     * @param shader The shader
     * @param draw_mode The draw mode
     * @param material The material
     * @param entity_id The entity id
     */
    void drawVAO(const atcg::ref_ptr<VertexArray>& vao,
                 const atcg::ref_ptr<Camera>& camera,
                 const glm::mat4& model,
                 const GraphicsPipeline& pipeline,
                 const size_t size,
                 const size_t instances = 1);

    /**
     * @brief Draw Circle
     *
     * @param position The position
     * @param radius The radius
     * @param thickness The thickness of the circle
     * @param color The color
     * @param camera The camera
     */
    void drawCircle(const glm::vec3& position,
                    const float& radius,
                    const float& thickness,
                    const glm::vec3& color,
                    const atcg::ref_ptr<Camera>& camera = {});

    /**
     * @brief Display an image/texture in the main viewport. It is assumed that the image resolution is the same as the
     * viewport resolution. This function can be used to display results generated with a custom framebuffer. However,
     * entity selection is only available if this framebuffer has an additional atcg::TextureFormat::RINT attachement in
     * slot 1.
     *
     * @param img The image to display
     */
    void drawImage(const atcg::ref_ptr<Framebuffer>& img);

    /**
     * @brief Display an image/texture in the main viewport. It is assumed that the image resolution is the same as the
     * viewport resolution. This function can be used to display results generated with a custom framebuffer. However,
     * entity selection is only possible if an additional entity map is given as RINT.
     *
     * @param img The image to display
     * @param entity_ids The entity id map
     */
    void drawImage(const atcg::ref_ptr<Texture2D>& img, const atcg::ref_ptr<Texture2D>& entity_ids = nullptr);

    /**
     * @brief Draws a CAD grid with three resolutions (0.1, 1, 10)
     *
     * @param camera The camera
     * @param transparency The transparency of the grid
     */
    void drawCADGrid(const atcg::ref_ptr<Camera>& camera, const float& transparency = 0.6f);

    /**
     * @brief Get the framebuffer objects that is used by the renderer.
     * Depending on if MSAA is enabled or not, this may be a MSAA framebuffer that can only be used for additional
     * rendering tasks. Data reads can not be performed in this case.
     *
     * @return The framebuffer of last frame
     */
    atcg::ref_ptr<Framebuffer> getFramebuffer() const;

    /**
     * @brief Get the shader manager associated with this renderer
     *
     * @return The shader manager
     */
    atcg::ref_ptr<ShaderManagerSystem> getShaderManager() const;

    RendererSystem();

    ~RendererSystem();

private:
    class Impl;
    atcg::scope_ptr<Impl> impl;
};

/**
 * @brief This namespace encapsulates the default renderer of this framework.
 */
namespace Renderer
{
/**
 * @brief Initializes the renderer (should not be called by the client!)
 *
 * @param width The width
 * @param height The height
 * @param context The context
 * @param shader_manager The shader manager associated with this renderer
 */
ATCG_INLINE void init(uint32_t width,
                      uint32_t height,
                      const atcg::ref_ptr<Context>& context,
                      const atcg::ref_ptr<ShaderManagerSystem>& shader_manager)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->init(width, height, context, shader_manager);
}

/**
 * @brief Use this instance of the renderer.
 * This only needs to be called if multiple renderer instances are in use or multi thread rendering is desired. This
 * function will make the underlying context current for the thread.
 */
ATCG_INLINE void use()
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->use();
}

/**
 * @brief Finished the currently drawn frame (should not be called by client!)
 */
ATCG_INLINE void finishFrame()
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->finishFrame();
}

/**
 * @brief Stalls the CPU until all rendering requests are finished
 */
ATCG_INLINE void finish()
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->finish();
}

/**
 * @brief Change the size of the renderer
 *
 * @param width The width
 * @param height The height
 */
ATCG_INLINE void resize(const uint32_t& width, const uint32_t& height)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->resize(width, height);
}

/**
 * @brief Render a mesh
 *
 * The default draw mode is "base". It applys slight shading based on the vertex normals.
 * An optional color can be given to color the whole mesh with a constant color.
 * If given a custom shader, color is ignored except if the shader variable "flat_color" is used.
 *
 * For ATCG_DRAW_MDOE_SPHERE The custom shader has to implement an instance rendering scheme like the "base" shader.
 * If no custom shader is to be used, stick to the "base" shader. For ATCG_DRAW_MODE_EDGE and
 * ATCG_DRAW_MODE_CYLINDER, you can pass nullptr for the shader to use the built in "edge" and "edge_cylinder"
 * shader. If a custom shader should be used, it has to implement the basic instancing the is used in the
 * aforementioned shaders.
 *
 * @param mesh The mesh
 * @param camera The camera
 * @param model The optional model matrix
 * @param color An optional color
 * @param shader The shader
 * @param draw_mode The draw mode
 * @param material The material
 * @param entity_id The entity id
 */
ATCG_INLINE void drawVAO(const atcg::ref_ptr<VertexArray>& vao,
                         const atcg::ref_ptr<Camera>& camera,
                         const glm::mat4& model,
                         const GraphicsPipeline& pipeline,
                         const size_t size,
                         const size_t instances = 1)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->drawVAO(vao, camera, model, pipeline, size, instances);
}

/**
 * @brief Draw Circle
 *
 * @param position The position
 * @param radius The radius
 * @param thickness The thickness of the circle
 * @param color The color
 * @param camera The camera
 */
ATCG_INLINE void drawCircle(const glm::vec3& position,
                            const float& radius,
                            const float& thickness,
                            const glm::vec3& color,
                            const atcg::ref_ptr<Camera>& camera = {})
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->drawCircle(position, radius, thickness, color, camera);
}

/**
 * @brief Draws a CAD grid with three resolutions (0.1, 1, 10)
 *
 * @param camera The camera
 * @param transparency The transparency of the grid
 */
ATCG_INLINE void drawCADGrid(const atcg::ref_ptr<Camera>& camera, const float& transparency = 0.6f)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->drawCADGrid(camera, transparency);
}

/**
 * @brief Display an image/texture in the main viewport. It is assumed that the image resolution is the same as the
 * viewport resolution. This function can be used to display results generated with a custom framebuffer. However,
 * entity selection is only available if this framebuffer has an additional atcg::TextureFormat::RINT attachement in
 * slot 1.
 *
 * @param img The image to display
 */
ATCG_INLINE void drawImage(const atcg::ref_ptr<Framebuffer>& img)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->drawImage(img);
}

/**
 * @brief Display an image/texture in the main viewport. It is assumed that the image resolution is the same as the
 * viewport resolution. This function can be used to display results generated with a custom framebuffer. However,
 * entity selection is only possible if an additional entity map is given as RINT.
 *
 * @param img The image to display
 * @param entity_ids The entity id map
 */
ATCG_INLINE void drawImage(const atcg::ref_ptr<Texture2D>& img, const atcg::ref_ptr<Texture2D>& entity_ids = nullptr)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->drawImage(img, entity_ids);
}

/**
 * @brief Get the framebuffer objects that is used by the renderer.
 * This framebuffer does not represent the current frame but the last frame after finishFrame() was called. To get
 * the current frame data, refer to getFramebufferMSAA().
 * Any direct draw call done to this framebuffer will be overwritten at the end of the current frame by the blit
 * operation on the msaa buffer. If direct rendering to this framebuffer is desired, MSAA has to be toggle off using
 * toggleMSAA.
 *
 * @return The framebuffer of last frame
 */
ATCG_INLINE atcg::ref_ptr<Framebuffer> getFramebuffer()
{
    return SystemRegistry::instance()->getSystem<RendererSystem>()->getFramebuffer();
}

/**
 * @brief Get the current frame counter
 *
 * @return The index of the current frame
 */
ATCG_INLINE uint32_t getFrameCounter()
{
    return SystemRegistry::instance()->getSystem<RendererSystem>()->getFrameCounter();
}

/**
 * @brief Generates a new texture ID that is not used yet.
 * The renderer internally uses a fixed set of render IDs that should not be used by the client. This function
 * guarantees that the given texture id is not yet taken (unless manual texture ids are created). If a texture id is
 * no longer in use, it should be released with pushTextureID.
 *
 * @return The texture ID
 */
ATCG_INLINE uint32_t popTextureID()
{
    return SystemRegistry::instance()->getSystem<RendererSystem>()->popTextureID();
}

/**
 * @brief Free a texture ID.
 * Should only be used on ids that were generated using popTextureID. Adding other IDs may break the system because
 * some ids are reserved for the internals of the Renderer.
 *
 * @param id The id generated by popTextureID
 */
ATCG_INLINE void pushTextureID(const uint32_t id)
{
    SystemRegistry::instance()->getSystem<RendererSystem>()->pushTextureID(id);
}

/**
 * @brief Get the shader manager associated with this renderer
 *
 * @return The shader manager
 */
ATCG_INLINE atcg::ref_ptr<ShaderManagerSystem> getShaderManager()
{
    return SystemRegistry::instance()->getSystem<RendererSystem>()->getShaderManager();
}
}    // namespace Renderer

}    // namespace atcg