#pragma once

#include <Scene/Components/AccelerationStructureComponent.h>
#include <Scene/Components/CameraComponent.h>
#include <Scene/Components/CustomRenderComponent.h>
#include <Scene/Components/EdgeCylinderRenderComponent.h>
#include <Scene/Components/EdgeRenderComponent.h>
#include <Scene/Components/EditorCameraComponent.h>
#include <Scene/Components/GeometryComponent.h>
#include <Scene/Components/IDComponent.h>
#include <Scene/Components/InstanceRenderComponent.h>
#include <Scene/Components/MediumComponent.h>
#include <Scene/Components/MeshLightComponent.h>
#include <Scene/Components/MeshRenderComponent.h>
#include <Scene/Components/NameComponent.h>
#include <Scene/Components/PointLightComponent.h>
#include <Scene/Components/PointRenderComponent.h>
#include <Scene/Components/PointSphereRenderComponent.h>
#include <Scene/Components/RenderComponent.h>
#include <Scene/Components/ScriptComponent.h>
#include <Scene/Components/TransformComponent.h>
#include <Scene/Components/TransparencyComponent.h>