name: CMake

on:
  push:
    branches: [ "main", "exercises", "dev" ]
  pull_request:
    branches: [ "main", "exercises", "dev" ]

jobs:
  ubuntu-build:
    name: Ubuntu Compile Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - run: sudo apt-get -y update
      - run: sudo apt-get install mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev xorg-dev
      - run: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      - run: cmake -B ./build -S .
      - run: cmake --build build
  
  windows-build:
    name: Windows Compile Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - run: pip install torch torchvision torchaudio
      - run: cmake -B ./build -S .
      - run: cmake --build build
      
  #macos-build:
  #  name: MacOS Compile Check
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@main
  #      with:
  #        submodules: recursive
  #    - run: cmake -B ./build -S .
  #    - run: cmake --build build
      
